/**
 * Turns technical failures into sentences a language model can act on.
 *
 * For an MCP server the error message is part of the interface: it ends up in
 * the model's context, which then has to work out what to do next.
 * "ECONNREFUSED 127.0.0.1:1143" does not help with that.
 */

export class BridgeError extends Error {
  override name = 'BridgeError'
}

interface ErrorWithCode {
  code?: string
  responseText?: string
  message?: string
}

/**
 * Builds an understandable message from an arbitrary failure.
 *
 * `host` and `port` appear in the text because the ports are configurable and
 * a wrong port is the second most common cause.
 */
export function explainError(error: unknown, host: string, port: number): BridgeError {
  const e = error as ErrorWithCode
  const address = `${host}:${port}`

  if (e?.code === 'ECONNREFUSED') {
    return new BridgeError(
      `Nothing is accepting connections on ${address}. Proton Mail Bridge is probably not running. ` +
        'Start the Bridge application and sign in. ' +
        'If it is running, check Settings, Advanced whether it uses a different port, ' +
        'and set BRIDGE_IMAP_PORT accordingly.',
      { cause: error },
    )
  }

  if (e?.code === 'ETIMEDOUT' || e?.code === 'ECONNRESET') {
    return new BridgeError(
      `The connection to ${address} did not come up, or it was dropped. ` +
        'That happens while the Bridge is starting up or while it is locked. Check that it is unlocked and try again.',
      { cause: error },
    )
  }

  if (e?.code === 'ENOTFOUND' || e?.code === 'EAI_AGAIN') {
    return new BridgeError(
      `The address "${host}" could not be resolved. The Bridge always runs locally, ` +
        'so BRIDGE_HOST should be 127.0.0.1.',
      { cause: error },
    )
  }

  // imapflow reports rejected logins as AUTHENTICATIONFAILED.
  const text = `${e?.responseText ?? ''} ${e?.message ?? ''}`
  if (/AUTHENTICATIONFAILED|Invalid credentials|LOGIN failed/i.test(text)) {
    return new BridgeError(
      'The Bridge rejected the login. It expects the password generated by the Bridge, ' +
        'not the password of your Proton account. You can find it in the Bridge application for the account in question. ' +
        'Also check that BRIDGE_USER is exactly the address configured there.',
      { cause: error },
    )
  }

  if (/certificate|self.signed|DEPTH_ZERO/i.test(text)) {
    return new BridgeError(
      'The Bridge certificate was rejected. The Bridge uses a self-signed certificate, ' +
        'which is only accepted for connections to 127.0.0.1.',
      { cause: error },
    )
  }

  const raw = e?.message ?? String(error)
  return new BridgeError(`The Bridge reported an error: ${raw}`, { cause: error })
}
